const express = require("express");
const twilio = require("twilio");

const app = express();

app.use(express.urlencoded({ extended: false }));
app.use(express.json());

const BASE_URL = "https://call-voice-twilio.onrender.com";

const ELEVENLABS_API_KEY = process.env.ELEVENLABS_API_KEY;
const ELEVENLABS_AGENT_NOVA = process.env.ELEVENLABS_AGENT_NOVA;
const ELEVENLABS_AGENT_VICTORIA = process.env.ELEVENLABS_AGENT_VICTORIA;

const systemVoice = {
  voice: "alice",
  language: "en-US",
};

const NUMBERS = {
  MAIN_SUPPORT: {
    label: "Lukintosh Main Support",
    publicName: "United States and Canada Main Support",
    number: "+18007533988",
    displayNumber: "+1 800-753-3988",
    endpoint: "/voice/main-support",
    agentName: "Nova",
    agentEnvKey: "ELEVENLABS_AGENT_NOVA",
  },
  BUSINESS: {
    label: "Lukintosh Business",
    publicName: "Business and Corporate Inquiries",
    number: "+18885852819",
    displayNumber: "+1 888-LUK-2819 / +1 888-585-2819",
    endpoint: "/voice/business",
    agentName: "Victoria",
    agentEnvKey: "ELEVENLABS_AGENT_VICTORIA",
  },
};

function twiml() {
  return new twilio.twiml.VoiceResponse();
}

function send(res, response) {
  res.type("text/xml");
  res.send(response.toString());
}

function normalizeNumber(value = "") {
  return String(value).replace(/[^\d]/g, "");
}

function detectLineFromTwilioTo(to = "") {
  const clean = normalizeNumber(to);

  if (clean.endsWith("18007533988") || clean.endsWith("8007533988")) {
    return "MAIN_SUPPORT";
  }

  if (clean.endsWith("18885852819") || clean.endsWith("8885852819")) {
    return "BUSINESS";
  }

  return "MAIN_SUPPORT";
}

function getLine(lineKey = "MAIN_SUPPORT") {
  return NUMBERS[lineKey] || NUMBERS.MAIN_SUPPORT;
}

function getAgentId(lineKey = "MAIN_SUPPORT") {
  if (lineKey === "BUSINESS") return ELEVENLABS_AGENT_VICTORIA;
  return ELEVENLABS_AGENT_NOVA;
}

/* ============================================================
   12-SECOND HOLD MUSIC GENERATED BY NODE
   ============================================================ */

function createWavHeader(dataLength, sampleRate, channels, bitsPerSample) {
  const buffer = Buffer.alloc(44);

  const byteRate = (sampleRate * channels * bitsPerSample) / 8;
  const blockAlign = (channels * bitsPerSample) / 8;

  buffer.write("RIFF", 0);
  buffer.writeUInt32LE(36 + dataLength, 4);
  buffer.write("WAVE", 8);

  buffer.write("fmt ", 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(channels, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(byteRate, 28);
  buffer.writeUInt16LE(blockAlign, 32);
  buffer.writeUInt16LE(bitsPerSample, 34);

  buffer.write("data", 36);
  buffer.writeUInt32LE(dataLength, 40);

  return buffer;
}

function generateLukintoshHoldMusic() {
  const sampleRate = 8000;
  const durationSeconds = 12;
  const channels = 1;
  const bitsPerSample = 16;

  const totalSamples = sampleRate * durationSeconds;
  const dataLength = totalSamples * 2;
  const audio = Buffer.alloc(dataLength);

  const chords = [
    [261.63, 329.63, 392.0],
    [293.66, 349.23, 440.0],
    [329.63, 392.0, 493.88],
    [349.23, 440.0, 523.25],
  ];

  for (let i = 0; i < totalSamples; i++) {
    const t = i / sampleRate;
    const chord = chords[Math.floor(t / 3) % chords.length];

    let sample = 0;

    for (const freq of chord) {
      sample += Math.sin(2 * Math.PI * freq * t) * 0.16;
    }

    sample += Math.sin(2 * Math.PI * 110 * t) * 0.05;

    const fadeIn = Math.min(1, t / 1.2);
    const fadeOut = Math.min(1, (durationSeconds - t) / 1.2);
    const envelope = Math.min(fadeIn, fadeOut);

    sample *= envelope * 0.35;

    const intSample = Math.max(-1, Math.min(1, sample)) * 32767;
    audio.writeInt16LE(intSample, i * 2);
  }

  const header = createWavHeader(dataLength, sampleRate, channels, bitsPerSample);
  return Buffer.concat([header, audio]);
}

app.get("/audio/lukintosh-hold-12s.wav", (req, res) => {
  const wav = generateLukintoshHoldMusic();

  res.setHeader("Content-Type", "audio/wav");
  res.setHeader("Content-Length", wav.length);
  res.setHeader("Cache-Control", "no-store");

  res.send(wav);
});

/* ============================================================
   HOME
   ============================================================ */

app.get("/", (req, res) => {
  res.send(`
    <h1>Lukintosh Voice Support</h1>
    <p>Status: online</p>

    <h2>Official Numbers</h2>
    <ul>
      <li><strong>Main Support:</strong> ${NUMBERS.MAIN_SUPPORT.displayNumber} → Nova</li>
      <li><strong>Business:</strong> ${NUMBERS.BUSINESS.displayNumber} → Victoria</li>
    </ul>

    <h2>Twilio Webhooks</h2>
    <ul>
      <li><a href="/voice/main-support">/voice/main-support</a> — 1-800 Main Support</li>
      <li><a href="/voice/business">/voice/business</a> — 1-888 Business</li>
      <li><a href="/audio/lukintosh-hold-12s.wav">/audio/lukintosh-hold-12s.wav</a> — 12s hold music</li>
    </ul>

    <h2>Environment</h2>
    <ul>
      <li>ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY ? "set" : "missing"}</li>
      <li>ELEVENLABS_AGENT_NOVA: ${ELEVENLABS_AGENT_NOVA ? "set" : "missing"}</li>
      <li>ELEVENLABS_AGENT_VICTORIA: ${ELEVENLABS_AGENT_VICTORIA ? "set" : "missing"}</li>
    </ul>
  `);
});

/* ============================================================
   STEP 1 — ALICE ANSWERS
   ============================================================ */

function buildMainMenu(lineKey = "MAIN_SUPPORT") {
  const r = twiml();
  const line = getLine(lineKey);

  r.pause({ length: 1 });

  r.say(systemVoice, "Thank you for calling Lukintosh Corporation.");

  if (lineKey === "BUSINESS") {
    r.say(systemVoice, "You have reached Lukintosh Business and Corporate Inquiries.");
  } else {
    r.say(systemVoice, "You have reached Lukintosh Main Support for the United States and Canada.");
  }

  r.say(
    systemVoice,
    "Your call may be monitored or recorded for quality, training, security, and service improvement purposes."
  );

  const gather = r.gather({
    input: "dtmf",
    numDigits: 1,
    timeout: 8,
    action: `${BASE_URL}/language?line=${lineKey}`,
    method: "POST",
  });

  gather.say(systemVoice, "For English, press 1. Para portugues, press 2.");

  r.redirect({ method: "POST" }, `${BASE_URL}${line.endpoint}`);

  return r;
}

app.get("/voice", (req, res) => {
  const lineKey = detectLineFromTwilioTo(req.query.To || "");
  send(res, buildMainMenu(lineKey));
});

app.post("/voice", (req, res) => {
  const lineKey = detectLineFromTwilioTo(req.body.To || "");
  send(res, buildMainMenu(lineKey));
});

app.get("/voice/main-support", (req, res) => {
  send(res, buildMainMenu("MAIN_SUPPORT"));
});

app.post("/voice/main-support", (req, res) => {
  send(res, buildMainMenu("MAIN_SUPPORT"));
});

app.get("/voice/business", (req, res) => {
  send(res, buildMainMenu("BUSINESS"));
});

app.post("/voice/business", (req, res) => {
  send(res, buildMainMenu("BUSINESS"));
});

/* ============================================================
   STEP 2 — LANGUAGE
   ============================================================ */

app.post("/language", (req, res) => {
  const r = twiml();

  const digit = req.body.Digits;
  const lineKey = req.query.line || "MAIN_SUPPORT";

  if (digit !== "1") {
    r.say(
      systemVoice,
      "Portuguese support is not available on this line yet. Continuing in English."
    );
  }

  r.say(systemVoice, "Thank you. Before we continue, we need some information.");

  const gather = r.gather({
    input: "dtmf",
    numDigits: 1,
    timeout: 10,
    action: `${BASE_URL}/department?line=${lineKey}`,
    method: "POST",
  });

  if (lineKey === "BUSINESS") {
    gather.say(systemVoice, "For partnerships and commercial opportunities, press 1.");
    gather.say(systemVoice, "For developer relations, press 2.");
    gather.say(systemVoice, "For media and press inquiries, press 3.");
    gather.say(systemVoice, "For legal, trust, or compliance matters, press 4.");
    gather.say(systemVoice, "For general corporate information, press 5.");
  } else {
    gather.say(systemVoice, "For Yeux accessibility and eye tracking support, press 1.");
    gather.say(systemVoice, "For developer tools, APIs, and platform services, press 2.");
    gather.say(systemVoice, "For Lukintosh Accounts and sign in support, press 3.");
    gather.say(systemVoice, "For security and account protection, press 4.");
    gather.say(systemVoice, "For another support request, press 5.");
  }

  r.redirect({ method: "POST" }, `${BASE_URL}/language?line=${lineKey}`);

  send(res, r);
});

/* ============================================================
   STEP 3 — DEPARTMENT
   ============================================================ */

app.post("/department", (req, res) => {
  const r = twiml();

  const lineKey = req.query.line || "MAIN_SUPPORT";
  const department = req.body.Digits || "unknown";

  r.say(systemVoice, "Thank you.");

  const gather = r.gather({
    input: "dtmf",
    numDigits: 6,
    timeout: 12,
    action: `${BASE_URL}/support-code?line=${lineKey}&department=${department}`,
    method: "POST",
  });

  gather.say(
    systemVoice,
    "Please enter your six digit support code or ticket number. If you do not have one, enter zero zero zero zero zero zero."
  );

  r.redirect(
    { method: "POST" },
    `${BASE_URL}/support-code?line=${lineKey}&department=${department}`
  );

  send(res, r);
});

/* ============================================================
   STEP 4 — SUPPORT CODE THEN CONNECT TO ELEVENLABS
   ============================================================ */

app.post("/support-code", (req, res) => {
  const r = twiml();

  const lineKey = req.query.line || "MAIN_SUPPORT";
  const ticket = req.body.Digits || "000000";

  r.say(
    systemVoice,
    `Thank you. Your reference code is ${ticket.split("").join(" ")}.`
  );

  r.say(systemVoice, "Please hold while I connect you with a Lukintosh representative.");

  r.play(`${BASE_URL}/audio/lukintosh-hold-12s.wav`);

  r.redirect(
    { method: "POST" },
    `${BASE_URL}/connect-agent?line=${lineKey}&ticket=${encodeURIComponent(ticket)}&department=${encodeURIComponent(req.query.department || "unknown")}`
  );

  send(res, r);
});

/* ============================================================
   STEP 5 — REGISTER TWILIO CALL WITH ELEVENLABS
   ============================================================ */

app.post("/connect-agent", async (req, res) => {
  const lineKey = req.query.line || "MAIN_SUPPORT";
  const line = getLine(lineKey);
  const agentId = getAgentId(lineKey);

  const callerNumber = req.body.From || req.query.From || "+15555550123";
  const calledNumber = req.body.To || line.number;

  console.log("DEBUG connect-agent incoming:", {
    lineKey,
    line: line.label,
    agentName: line.agentName,
    hasApiKey: !!ELEVENLABS_API_KEY,
    agentIdPresent: !!agentId,
    agentIdPreview: agentId ? `${agentId.slice(0, 8)}...` : "missing",
    callerNumber,
    calledNumber,
    ticket: req.query.ticket,
    department: req.query.department,
  });

  if (!ELEVENLABS_API_KEY || !agentId) {
    res.status(500).type("application/json");
    return res.send({
      ok: false,
      error: "missing_config",
      hasApiKey: !!ELEVENLABS_API_KEY,
      agentIdPresent: !!agentId,
      lineKey,
    });
  }

  try {
    const payload = {
      agent_id: agentId,
      from_number: callerNumber,
      to_number: calledNumber,
      direction: "inbound",
    };

    console.log("DEBUG ElevenLabs payload:", {
      ...payload,
      agent_id: `${agentId.slice(0, 8)}...`,
    });

    const response = await fetch(
      "https://api.elevenlabs.io/v1/convai/twilio/register-call",
      {
        method: "POST",
        headers: {
          "xi-api-key": ELEVENLABS_API_KEY,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      }
    );

    const responseText = await response.text();

    console.log("DEBUG ElevenLabs response:", {
      status: response.status,
      ok: response.ok,
      body: responseText,
    });

    if (!response.ok) {
      res.status(500).type("application/json");
      return res.send({
        ok: false,
        error: "elevenlabs_register_call_failed",
        status: response.status,
        body: responseText,
      });
    }

    res.type("text/xml");
    return res.send(responseText);
  } catch (error) {
    console.error("DEBUG connect-agent exception:", error);

    res.status(500).type("application/json");
    return res.send({
      ok: false,
      error: "exception",
      message: error.message,
    });
  }
});

    const response = await fetch(
      "https://api.elevenlabs.io/v1/convai/twilio/register-call",
      {
        method: "POST",
        headers: {
          "xi-api-key": ELEVENLABS_API_KEY,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          agent_id: agentId,
          from_number: callerNumber,
          to_number: calledNumber,
        }),
      }
    );

    const twimlText = await response.text();

    if (!response.ok) {
      console.error("ElevenLabs register-call error:", response.status, twimlText);

      const r = twiml();
      r.say(
        systemVoice,
        "I could not connect you with the AI representative right now. Please try again later."
      );
      r.hangup();
      return send(res, r);
    }

    res.type("text/xml");
    res.send(twimlText);
  } catch (error) {
    console.error("Connect agent error:", error);

    const r = twiml();
    r.say(
      systemVoice,
      "I could not connect you with the AI representative right now. Please try again later."
    );
    r.hangup();
    send(res, r);
  }
});

/* ============================================================
   TEST ENDPOINTS
   ============================================================ */

app.get("/test/connect-main", async (req, res) => {
  req.query.line = "MAIN_SUPPORT";
  req.body = {
    From: "+15555550123",
    To: "+18007533988",
  };

  app._router.handle(req, res, () => {}, "/connect-agent");
});

app.get("/test/connect-business", async (req, res) => {
  req.query.line = "BUSINESS";
  req.body = {
    From: "+15555550123",
    To: "+18885852819",
  };

  app._router.handle(req, res, () => {}, "/connect-agent");
});

/* ============================================================
   SERVER
   ============================================================ */

const PORT = process.env.PORT || 8080;

app.listen(PORT, () => {
  console.log(`Lukintosh Voice Support running on port ${PORT}`);
  console.log(`Main Support endpoint: ${NUMBERS.MAIN_SUPPORT.endpoint}`);
  console.log(`Business endpoint: ${NUMBERS.BUSINESS.endpoint}`);
  console.log(`Hold music: ${BASE_URL}/audio/lukintosh-hold-12s.wav`);
});
