const express = require("express");
const twilio = require("twilio");

const app = express();

app.use(express.urlencoded({ extended: false }));
app.use(express.json());

const BASE_URL = "https://call-voice-twilio.onrender.com";

// Voz institucional da URA
const systemVoice = { voice: "alice", language: "en-US" };

// Vozes dos representantes.
// Se alguma voz não funcionar na Twilio, troque por "Polly.Joanna" ou "woman".
const representativeVoices = {
  NOVA: { voice: "Polly.Joanna-Neural", language: "en-US" },
  VICTORIA: { voice: "Polly.Amy-Neural", language: "en-GB" },
};

const NUMBERS = {
  MAIN_SUPPORT: {
    label: "Lukintosh Main Support",
    publicName: "United States and Canada Main Support",
    number: "1-800-753-3988",
    endpoint: "/voice/main-support",
    representativeName: "Nova",
    representativeKey: "NOVA",
    representativeTitle: "automated representative for Lukintosh Main Support",
  },
  BUSINESS: {
    label: "Lukintosh Business",
    publicName: "Business and Corporate Inquiries",
    number: "1-888-LUK-2819",
    numericNumber: "1-888-585-2819",
    endpoint: "/voice/business",
    representativeName: "Victoria",
    representativeKey: "VICTORIA",
    representativeTitle:
      "automated representative for Lukintosh Business and Corporate Inquiries",
  },
};

function twiml() {
  return new twilio.twiml.VoiceResponse();
}

function send(res, response) {
  res.type("text/xml");
  res.send(response.toString());
}

function normalizeNumber(value = "") {
  return String(value).replace(/[^\d]/g, "");
}

function detectLineFromTwilioTo(to = "") {
  const clean = normalizeNumber(to);

  // +1 800-753-3988
  if (clean.endsWith("18007533988") || clean.endsWith("8007533988")) {
    return "MAIN_SUPPORT";
  }

  // +1 888-LUK-2819 = +1 888-585-2819
  if (clean.endsWith("18885852819") || clean.endsWith("8885852819")) {
    return "BUSINESS";
  }

  return "MAIN_SUPPORT";
}

function getLine(lineKey = "MAIN_SUPPORT") {
  return NUMBERS[lineKey] || NUMBERS.MAIN_SUPPORT;
}

function getRepresentativeVoice(lineKey = "MAIN_SUPPORT") {
  const line = getLine(lineKey);
  return representativeVoices[line.representativeKey] || systemVoice;
}

/* ============================================================
   LUKINTOSH HOLD MUSIC - 12 SECONDS, GENERATED BY NODE
   ============================================================ */

function createWavHeader(dataLength, sampleRate, channels, bitsPerSample) {
  const buffer = Buffer.alloc(44);

  const byteRate = (sampleRate * channels * bitsPerSample) / 8;
  const blockAlign = (channels * bitsPerSample) / 8;

  buffer.write("RIFF", 0);
  buffer.writeUInt32LE(36 + dataLength, 4);
  buffer.write("WAVE", 8);

  buffer.write("fmt ", 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(channels, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(byteRate, 28);
  buffer.writeUInt16LE(blockAlign, 32);
  buffer.writeUInt16LE(bitsPerSample, 34);

  buffer.write("data", 36);
  buffer.writeUInt32LE(dataLength, 40);

  return buffer;
}

function generateLukintoshHoldMusic() {
  const sampleRate = 8000;
  const durationSeconds = 12;
  const channels = 1;
  const bitsPerSample = 16;

  const totalSamples = sampleRate * durationSeconds;
  const dataLength = totalSamples * 2;
  const audio = Buffer.alloc(dataLength);

  const chords = [
    [261.63, 329.63, 392.0],
    [293.66, 349.23, 440.0],
    [329.63, 392.0, 493.88],
    [349.23, 440.0, 523.25],
  ];

  for (let i = 0; i < totalSamples; i++) {
    const t = i / sampleRate;
    const chordIndex = Math.floor(t / 3) % chords.length;
    const chord = chords[chordIndex];

    let sample = 0;

    for (const freq of chord) {
      sample += Math.sin(2 * Math.PI * freq * t) * 0.16;
    }

    sample += Math.sin(2 * Math.PI * 110 * t) * 0.05;

    const fadeIn = Math.min(1, t / 1.2);
    const fadeOut = Math.min(1, (durationSeconds - t) / 1.2);
    const envelope = Math.min(fadeIn, fadeOut);

    sample *= envelope * 0.35;

    const intSample = Math.max(-1, Math.min(1, sample)) * 32767;
    audio.writeInt16LE(intSample, i * 2);
  }

  const header = createWavHeader(
    dataLength,
    sampleRate,
    channels,
    bitsPerSample
  );

  return Buffer.concat([header, audio]);
}

app.get("/audio/lukintosh-hold-12s.wav", (req, res) => {
  const wav = generateLukintoshHoldMusic();

  res.setHeader("Content-Type", "audio/wav");
  res.setHeader("Content-Length", wav.length);
  res.setHeader("Cache-Control", "no-store");

  res.send(wav);
});

/* ============================================================
   MAIN IVR MENU
   ============================================================ */

function buildMainMenu(lineKey = "MAIN_SUPPORT") {
  const r = twiml();
  const line = getLine(lineKey);
  const repVoice = getRepresentativeVoice(lineKey);

  r.pause({ length: 1 });

  // Alice: voz institucional
  r.say(systemVoice, "Thank you for calling Lukintosh Corporation.");

  // Representative: voz mais humana
  r.say(
    repVoice,
    `This is ${line.representativeName}, the ${line.representativeTitle}.`
  );

  if (lineKey === "BUSINESS") {
    r.say(
      repVoice,
      "I can help collect your information, route your inquiry, and create a business support record."
    );
  } else {
    r.say(
      repVoice,
      "I can help route your request, collect support details, and create a support record for the United States and Canada."
    );
  }

  r.say(
    systemVoice,
    "Your call may be monitored or recorded for quality, training, security, and service improvement purposes."
  );

  const lang = r.gather({
    numDigits: 1,
    timeout: 8,
    action: `${BASE_URL}/language?line=${lineKey}`,
    method: "POST",
  });

  lang.say(systemVoice, "For English, press 1. Para portugues, press 2.");

  r.redirect({ method: "POST" }, `${BASE_URL}${line.endpoint}`);

  return r;
}

/* ============================================================
   STATUS / PREVIEW ROUTES
   ============================================================ */

app.get("/", (req, res) => {
  res.send(`
    <h1>Lukintosh Voice Support</h1>
    <p>Status: online</p>

    <h2>Official Numbers</h2>
    <ul>
      <li><strong>Main Support:</strong> ${NUMBERS.MAIN_SUPPORT.number} — Representative: ${NUMBERS.MAIN_SUPPORT.representativeName}</li>
      <li><strong>Business:</strong> ${NUMBERS.BUSINESS.number} / ${NUMBERS.BUSINESS.numericNumber} — Representative: ${NUMBERS.BUSINESS.representativeName}</li>
    </ul>

    <h2>Twilio Webhooks</h2>
    <ul>
      <li><a href="/voice/main-support">/voice/main-support</a> — 1-800 Main Support</li>
      <li><a href="/voice/business">/voice/business</a> — 1-888 Business</li>
      <li><a href="/voice">/voice</a> — automatic fallback by Twilio To number</li>
      <li><a href="/audio/lukintosh-hold-12s.wav">/audio/lukintosh-hold-12s.wav</a> — 12-second generated hold music</li>
      <li><a href="/preview/main-support">/preview/main-support</a> — Main Support preview</li>
      <li><a href="/preview/business">/preview/business</a> — Business preview</li>
    </ul>
  `);
});

app.get("/preview", (req, res) => {
  send(res, buildPreview("MAIN_SUPPORT"));
});

app.get("/preview/main-support", (req, res) => {
  send(res, buildPreview("MAIN_SUPPORT"));
});

app.get("/preview/business", (req, res) => {
  send(res, buildPreview("BUSINESS"));
});

function buildPreview(lineKey = "MAIN_SUPPORT") {
  const r = twiml();
  const line = getLine(lineKey);
  const repVoice = getRepresentativeVoice(lineKey);

  r.say(systemVoice, "Thank you for calling Lukintosh Corporation.");

  r.say(
    repVoice,
    `This is ${line.representativeName}, the ${line.representativeTitle}.`
  );

  r.say(
    systemVoice,
    "Your call may be monitored or recorded for quality, training, security, and service improvement purposes."
  );

  r.say(systemVoice, "For English, press 1. Para portugues, press 2.");
  r.say(
    systemVoice,
    "Please listen carefully as our menu options have recently changed."
  );

  if (lineKey === "BUSINESS") {
    r.say(repVoice, "For business partnerships, press 1.");
    r.say(repVoice, "For developer relations, press 2.");
    r.say(repVoice, "For media and press inquiries, press 3.");
    r.say(repVoice, "For legal, compliance, or security matters, press 4.");
    r.say(repVoice, "For general corporate information, press 5.");
  } else {
    r.say(systemVoice, "For Lukintosh Accounts and sign in support, press 1.");
    r.say(
      systemVoice,
      "For Yeux accessibility and eye tracking support, press 2."
    );
    r.say(
      systemVoice,
      "For developer tools, APIs, and platform services, press 3."
    );
    r.say(
      systemVoice,
      "For security, abuse, and account protection, press 4."
    );
    r.say(
      systemVoice,
      "For company, media, and business information, press 5."
    );
  }

  r.say(repVoice, "Before we continue, I need to collect a few details.");
  r.say(systemVoice, "Please enter your six digit support code or ticket number.");

  r.say(
    repVoice,
    "Please hold for a moment while I route your request to the correct Lukintosh support channel."
  );

  r.play(`${BASE_URL}/audio/lukintosh-hold-12s.wav`);

  r.pause({ length: 1 });

  r.say(
    repVoice,
    "Thank you for waiting. I will now create a support record for your request."
  );

  r.say(repVoice, "Please leave your message after the tone.");

  return r;
}

/* ============================================================
   VOICE ENTRYPOINTS
   ============================================================ */

app.get("/voice", (req, res) => {
  const lineKey = detectLineFromTwilioTo(req.query.To || req.body?.To || "");
  send(res, buildMainMenu(lineKey));
});

app.post("/voice", (req, res) => {
  const lineKey = detectLineFromTwilioTo(req.body.To || "");
  send(res, buildMainMenu(lineKey));
});

app.get("/voice/main-support", (req, res) => {
  send(res, buildMainMenu("MAIN_SUPPORT"));
});

app.post("/voice/main-support", (req, res) => {
  send(res, buildMainMenu("MAIN_SUPPORT"));
});

app.get("/voice/business", (req, res) => {
  send(res, buildMainMenu("BUSINESS"));
});

app.post("/voice/business", (req, res) => {
  send(res, buildMainMenu("BUSINESS"));
});

/* ============================================================
   LANGUAGE MENU
   ============================================================ */

app.post("/language", (req, res) => {
  const r = twiml();

  const digit = req.body.Digits;
  const lineKey = req.query.line || "MAIN_SUPPORT";
  const line = getLine(lineKey);
  const repVoice = getRepresentativeVoice(lineKey);

  if (digit !== "1") {
    r.say(
      systemVoice,
      "Portuguese support is not available on this testing line yet. Continuing in English."
    );
  }

  r.say(
    repVoice,
    `You are now in the ${line.publicName} menu.`
  );

  r.say(
    systemVoice,
    "Please listen carefully as our menu options have recently changed."
  );

  const gather = r.gather({
    numDigits: 1,
    timeout: 10,
    action: `${BASE_URL}/department?line=${lineKey}`,
    method: "POST",
  });

  if (lineKey === "BUSINESS") {
    gather.say(repVoice, "For business partnerships, press 1.");
    gather.say(repVoice, "For developer relations, press 2.");
    gather.say(repVoice, "For media and press inquiries, press 3.");
    gather.say(repVoice, "For legal, compliance, or security matters, press 4.");
    gather.say(repVoice, "For general corporate information, press 5.");
  } else {
    gather.say(systemVoice, "For Lukintosh Accounts and sign in support, press 1.");
    gather.say(
      systemVoice,
      "For Yeux accessibility and eye tracking support, press 2."
    );
    gather.say(
      systemVoice,
      "For developer tools, APIs, and platform services, press 3."
    );
    gather.say(
      systemVoice,
      "For security, abuse, and account protection, press 4."
    );
    gather.say(
      systemVoice,
      "For company, media, and business information, press 5."
    );
  }

  r.redirect({ method: "POST" }, `${BASE_URL}/language?line=${lineKey}`);

  send(res, r);
});

/* ============================================================
   DEPARTMENT MENU
   ============================================================ */

app.post("/department", (req, res) => {
  const r = twiml();

  const lineKey = req.query.line || "MAIN_SUPPORT";
  const department = req.body.Digits || "unknown";
  const repVoice = getRepresentativeVoice(lineKey);

  r.say(repVoice, "Before we continue, I need to collect a few details.");

  const gather = r.gather({
    input: "dtmf",
    numDigits: 6,
    timeout: 12,
    action: `${BASE_URL}/account?line=${lineKey}&department=${department}`,
    method: "POST",
  });

  gather.say(
    systemVoice,
    "Please enter your six digit support code or ticket number. If you do not have one, enter zero zero zero zero zero zero."
  );

  r.redirect(
    { method: "POST" },
    `${BASE_URL}/account?line=${lineKey}&department=${department}`
  );

  send(res, r);
});

/* ============================================================
   ACCOUNT / TICKET CODE
   ============================================================ */

app.post("/account", (req, res) => {
  const r = twiml();

  const lineKey = req.query.line || "MAIN_SUPPORT";
  const department = req.query.department || "unknown";
  const ticket = req.body.Digits || "000000";
  const repVoice = getRepresentativeVoice(lineKey);

  r.say(
    repVoice,
    `Thank you. Your reference code is ${ticket.split("").join(" ")}.`
  );

  const gather = r.gather({
    input: "dtmf",
    numDigits: 1,
    timeout: 10,
    action: `${BASE_URL}/reason?line=${lineKey}&department=${department}&ticket=${ticket}`,
    method: "POST",
  });

  if (lineKey === "BUSINESS") {
    gather.say(repVoice, "For partnership or commercial opportunities, press 1.");
    gather.say(repVoice, "For developer platform or API inquiries, press 2.");
    gather.say(repVoice, "For media, press, or brand inquiries, press 3.");
    gather.say(repVoice, "For legal, trust, or compliance matters, press 4.");
    gather.say(repVoice, "For another business reason, press 5.");
  } else {
    gather.say(systemVoice, "For login or password issues, press 1.");
    gather.say(systemVoice, "For product setup or installation, press 2.");
    gather.say(systemVoice, "For billing or subscription information, press 3.");
    gather.say(systemVoice, "For technical errors, press 4.");
    gather.say(systemVoice, "For another reason, press 5.");
  }

  r.redirect(
    { method: "POST" },
    `${BASE_URL}/reason?line=${lineKey}&department=${department}&ticket=${ticket}`
  );

  send(res, r);
});

/* ============================================================
   REASON / HOLD MUSIC / RECORD
   ============================================================ */

app.post("/reason", (req, res) => {
  const r = twiml();

  const lineKey = req.query.line || "MAIN_SUPPORT";
  const line = getLine(lineKey);
  const repVoice = getRepresentativeVoice(lineKey);

  const department = req.query.department || "unknown";
  const ticket = req.query.ticket || "000000";
  const reason = req.body.Digits || "unknown";

  console.log("New support call:", {
    line: line.label,
    publicName: line.publicName,
    representative: line.representativeName,
    calledNumber: req.body.To,
    from: req.body.From,
    country: req.body.FromCountry,
    department,
    ticket,
    reason,
  });

  r.say(repVoice, "Thank you. I am checking your information.");
  r.pause({ length: 1 });

  r.say(
    repVoice,
    "Please hold for a moment while I route your request to the correct Lukintosh support channel."
  );

  r.play(`${BASE_URL}/audio/lukintosh-hold-12s.wav`);

  r.pause({ length: 1 });

  r.say(
    repVoice,
    "Thank you for waiting. I will now create a support record for your request."
  );

  if (lineKey === "BUSINESS") {
    r.say(
      repVoice,
      "Please leave a business message after the tone. Include your name, organization, email address, and a short description of your inquiry."
    );
  } else {
    r.say(
      repVoice,
      "Please leave a support message after the tone. Include your name, email address, phone number, and a short description of the issue."
    );
  }

  r.record({
    maxLength: 45,
    playBeep: true,
    transcribe: false,
    action: `${BASE_URL}/voicemail?line=${lineKey}&department=${department}&ticket=${ticket}&reason=${reason}`,
    method: "POST",
  });

  send(res, r);
});

/* ============================================================
   VOICEMAIL RECEIVED
   ============================================================ */

app.post("/voicemail", (req, res) => {
  const r = twiml();

  const lineKey = req.query.line || "MAIN_SUPPORT";
  const line = getLine(lineKey);
  const repVoice = getRepresentativeVoice(lineKey);

  console.log("Voicemail received:", {
    line: line.label,
    publicName: line.publicName,
    representative: line.representativeName,
    from: req.body.From,
    to: req.body.To,
    recordingUrl: req.body.RecordingUrl,
    duration: req.body.RecordingDuration,
    department: req.query.department,
    ticket: req.query.ticket,
    reason: req.query.reason,
  });

  r.say(repVoice, "Thank you. I have recorded your message.");
  r.say(
    repVoice,
    "A Lukintosh support record has been created for this call."
  );
  r.say(systemVoice, "Thank you for contacting Lukintosh. Goodbye.");
  r.hangup();

  send(res, r);
});

/* ============================================================
   SERVER
   ============================================================ */

const PORT = process.env.PORT || 8080;

app.listen(PORT, () => {
  console.log(`Lukintosh Voice Support running on port ${PORT}`);
  console.log(`Main Support endpoint: ${NUMBERS.MAIN_SUPPORT.endpoint}`);
  console.log(`Business endpoint: ${NUMBERS.BUSINESS.endpoint}`);
  console.log(`Hold music: ${BASE_URL}/audio/lukintosh-hold-12s.wav`);
});
